#routing_protocol_setup
---
- name: routing_protocol_setup
  hosts: routers
  gather_facts: no

  tasks:

    - name: Configure OSPF on R1
      ios_config:
        lines:
          - router ospf 1
          - network 10.11.1.0 0.0.0.3 area 0
          - network 10.11.2.0 0.0.0.3 area 0
          - network 192.168.10.0 0.0.0.255 area 0
          - network 192.168.20.0 0.0.0.255 area 0
      when: inventory_hostname == 'R1'
      become: yes
      become_method: enable

    - name: Configure OSPF on R2
      ios_config:
        lines:
          - router ospf 1
          - network 10.11.1.0 0.0.0.3 area 0
          - network 192.168.10.0 0.0.0.255 area 0
      when: inventory_hostname == 'R2'
      become: yes
      become_method: enable

    - name: Configure OSPF on R3
      ios_config:
        lines:
          - router ospf 1
          - network 10.11.2.0 0.0.0.3 area 0
          - network 192.168.20.0 0.0.0.255 area 0
      when: inventory_hostname == 'R3'
      become: yes
      become_method: enable

    - name: Writing to memory
      ios_config:
        lines:
          - do write memory
      become: yes
      become_method: enable

